name: deploy

on:
  push:
    branches:
      - 'development'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/collapse:development

  deploy:
    runs-on: ubuntu-latest
      -
        name: Set up QEMU
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/collapse:development && docker run -d -e SECRET_KEY=asdf DEBUG=1 -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/collapse:development
